version: "3.9"

services:
  gateway-api:
    build: ./gateway-api
    ports:
      - "8080:8080"
    depends_on:
      - signaling
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - game-net

  signaling:
    build: ./signaling
    ports:
      - "8081:8081"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - game-net

  game-host-agent:
    build: ./game-host-agent
    ports:
      - "8090:8090"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/health"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - game-net
    # Se in futuro abiliti uinput:
    # devices:
    #   - /dev/uinput:/dev/uinput

  client-demo:
    build: ./client-demo
    ports:
      - "8082:80"
    restart: always
    networks:
      - game-net

networks:
  game-net:
    driver: bridge
